name: module3_task0
jobs:
  lint-build-and-test:
    steps:
      - run: make help
on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 3,15 * * *'
    # 3PM every day, this workflow will run
